### PR TITLE
Added timeout for the next captcha

### PR DESCRIPTION
**Pull request by jborbik**
Added timeout to avoid multiple notifications when captcha is needed.

### CODE REVIEW

**Comment by tete1030** [comment]
Sorry for late reply. Can you describe in detail how multiple notifications show up? I have not noticed this problem.

**Comment by jborbik** [comment]
I switched to your original branch and am again observing the problem as I don't remember the details.
Let me come back to you as soon as I have something to share.

**Comment by jborbik** [comment]
I cannot reproduce the problem anymore, earlier it was very annoying... Maybe something changed on the Google side, I am not sure.

Seems that this PR is not needed, I am closing :)

**Comment by tete1030** [comment]
Anyway, thank you. If I myself should encounter this problem, I will merge this.

**Pull request closed without merging**
